from exprimidora.base_verb import BaseVerb
from exprimidora.verb import Verb

from exprimidora.irregulars.to_have import IrregularToHave
from exprimidora.irregulars.to_be_existing import IrregularToBeExisting
from exprimidora.irregulars.to_be_standing import IrregularToBeStanding

from exprimidora.regular_verb import RegularVerb

from exprimidora.regular_first_group import RegularFirstGroup
from exprimidora.regular_second_group import RegularSecondGroup
from exprimidora.regular_third_group import RegularThirdGroup
