from exprimidora.base_verb import BaseVerb
from exprimidora.verb import Verb

from exprimidora.irregular_to_be import IrregularToBe
from exprimidora.irregular_to_have import IrregularToHave

from exprimidora.regular_first_group import RegularFirstGroup
from exprimidora.regular_second_group import RegularSecondGroup
from exprimidora.regular_third_group import RegularThirdGroup
